TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
# ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB_INSTALLS += XPS8_0108.db
DB_INSTALLS += XPS8_0916.db
DB_INSTALLS += XPS8_1724.db
DB_INSTALLS += XPS8_2532.db
DB_INSTALLS += XPS8_3340.db

DB_INSTALLS += status_update_0108.db
DB_INSTALLS += status_update_0916.db
DB_INSTALLS += status_update_1724.db
DB_INSTALLS += status_update_2532.db
DB_INSTALLS += status_update_3340.db

#----------------------------------------------------
# Create and install (or just install)
# Archive files, templates, substitutions like this
ARCHIVE += XPS8_0108_archive.template
ARCHIVE += XPS8_0916_archive.template
ARCHIVE += XPS8_1724_archive.template
ARCHIVE += XPS8_2532_archive.template
ARCHIVE += XPS8_3340_archive.template

#----------------------------------------------------
# Create and install (or just install)
# Autosave request files, templates, substitutions like this
REQ     += XPS8_0108_autosave.template
REQ     += XPS8_0916_autosave.template
REQ     += XPS8_1724_autosave.template
REQ     += XPS8_2532_autosave.template
REQ     += XPS8_3340_autosave.template


include $(TOP)/configure/RULES
#----------------------------------------
# ADD RULES AFTER THIS LINE

